server:  port: 8081  servlet:     context-path: /webservice
oauth:
  clientId: client1
  clientSecret: abc123
  checkTokenUrl: http://localhost:8083/as/oauth/check_token #URL of authorization server's checkToken endpoint